### PR TITLE
Fix flaky tests on GitHub Actions?

### LINKED ISSUE #48: Tests failing after merging #47
Looks like the tests are failing, after I merged #47.

### PR DESCRIPTION
**Pull request by ydnar**
Fixes #48.

### CODE REVIEW

File: resolver.go [hunk 1]
```diff
@@ -240,7 +240,7 @@ func (r *Resolver) exchange(ctx context.Context, host, qname, qtype string, dept
 func (r *Resolver) exchangeIP(ctx context.Context, host, ip, qname, qtype string, depth int) (RRs, error) {
 	dtype := dns.StringToType[qtype]
 	if dtype == 0 {
-		dtype = dns.TypeA
```
Comment (cee-dub) [inline resolver.go:243]: This doesn't do weird things to the output when using `-w`?

**Review by cee-dub — APPROVED** [review]

File: resolver.go (hunk 1 above)
Comment (ydnar) [reply resolver.go:243]: I could try reverting this.

Comment (ydnar) [reply resolver.go]: Done. Tests pass. Will merge.
